from pymongo import MongoClient

client = MongoClient('<connection string>')
db = client["DB name"]
# you can also list databases => <b>client.list_database_names() </b>and then select

collection_name = db["collection_name"]
# you can also list collections => <b>client.list_collection_names() </b>and then select

collection_index = collection_name.create_index("category")

# now you can try to traverse/search/sort filtered by category
data = collection_index.find({"category": "food"}) # this search will be from the sub list generated by creating index

# method 1
for i in data:
  print(i)

# method 2
from pandas import DataFrame

data = df(data)
